# .github/workflows/check_spelling.yml
name: Lint
on:
  pull_request:
    branches: [ master ]
    paths:
    - '**.md'
jobs:
    markdownlint-cli:
        runs-on: ubuntu-latest
        steps:
        - uses: nosborn/github-action-markdown-cli@v1.1.1
            with:
                files: .